---
title: "Map"
author: "Fernando Cagua"
date: "10/1/2014"
output: html_document
---

```{r libraries}
library (ggplot2)
library (ggmap)
library (plyr)
library (dplyr)
library (plotKML)
library (lubridate)
library (doMC)
library (maptools)
library (maps)
library (grid)
library (xtable)
library (mapdata)
registerDoMC (cores =30)
```


```{r}
land <- read.csv ("../Raw Data/Map/MapMafia.csv", skip = 48) %>% tbl_df() %>%
  select (ID, trksegID, lat, lon)
isobath <- read.csv ("../Raw Data/Map/Isobaths.csv", skip = 60) %>% tbl_df() %>%
  select (ID, trksegID, lat, lon) %>%
  mutate (lat.lead = lead (lat), lon.lead = lead (lon))
receivers <- read.csv ("../Raw Data/Map/Receivers.csv", skip = 22, nrows = 19) %>% tbl_df() %>%
  select (ID, lat, lon, time)
tracks <- readGPX ("../Raw Data/Map/MafiaTracks.GPX")$tracks %>%
  ldply (function (x){
    return (x[[1]])
  }, .progress = "text") %>% tbl_df()

tracks <- mutate (tracks, datetime = as.POSIXct (time, format = "%Y-%m-%dT%H:%M:%SZ", tz = "Africa/Dar_es_Sallam"), date = floor_date (datetime, unit = "day")) %>%
  arrange (datetime)
```

Standarize the tracks
```{r}
tracks <- ddply (tracks, "date", function (x){
  intervals <- diff (x$datetime) %>% as.numeric () %>% c (NA)
  x$intervals <- intervals
  return (x)
}, .progress = "text") %>% tbl_df()

# Remove tracks with few observations
tracks <- ddply (tracks, "date", function (x){
  if (nrow(x) < 15) {
    return (NULL)
  } else {
    return (x)
  }
})

tracks.standard <- ddply (tracks, "date", function (x){
  if (all (x$intervals == 0, na.rm = T)) {
    return (NULL)
  } else {
    y <- data.frame (date = x$date[1],
                   datetime = approx (x$datetime, x$lat, xout = seq (min (x$datetime), max (x$datetime), by = "min"))$x,
                   lat = approx (x$datetime, x$lat, xout = seq (min (x$datetime), max (x$datetime), by = "min"))$y, 
                   lon = approx (x$datetime, x$lon, xout = seq (min (x$datetime), max (x$datetime), by = "min"))$y)
    return (y)
  }
}, .parallel = TRUE)

# Remove points too close to the camp (39.66468, -7.907893)
tracks.standard <- filter (tracks.standard, abs (lat - (-7.907893)) > 0.002773, abs(lon - 39.66468) > 0.00118)


```

Functions to draw the scale
```{r}
#
# Result #
#--------#
# Return a list whose elements are :
#   - rectangle : a data.frame containing the coordinates to draw the first rectangle ;
#   - rectangle2 : a data.frame containing the coordinates to draw the second rectangle ;
#   - legend : a data.frame containing the coordinates of the legend texts, and the texts as well.
#
# Arguments : #
#-------------#
# lon, lat : longitude and latitude of the bottom left point of the first rectangle to draw ;
# distanceLon : length of each rectangle ;
# distanceLat : width of each rectangle ;
# distanceLegend : distance between rectangles and legend texts ;
# dist.units : units of distance "km" (kilometers) (default), "nm" (nautical miles), "mi" (statute miles).
createScaleBar <- function(lon,lat,distanceLon,distanceLat,distanceLegend, dist.units = "km"){
    # First rectangle
    bottomRight <- gcDestination(lon = lon, lat = lat, bearing = 90, dist = distanceLon, dist.units = dist.units, model = "WGS84")
     
    topLeft <- gcDestination(lon = lon, lat = lat, bearing = 0, dist = distanceLat, dist.units = dist.units, model = "WGS84")
    rectangle <- cbind(lon=c(lon, lon, bottomRight[1,"long"], bottomRight[1,"long"], lon),
    lat = c(lat, topLeft[1,"lat"], topLeft[1,"lat"],lat, lat))
    rectangle <- data.frame(rectangle, stringsAsFactors = FALSE)
     
    # Second rectangle t right of the first rectangle
    bottomRight2 <- gcDestination(lon = lon, lat = lat, bearing = 90, dist = distanceLon*2, dist.units = dist.units, model = "WGS84")
    rectangle2 <- cbind(lon = c(bottomRight[1,"long"], bottomRight[1,"long"], bottomRight2[1,"long"], bottomRight2[1,"long"], bottomRight[1,"long"]),
    lat=c(lat, topLeft[1,"lat"], topLeft[1,"lat"], lat, lat))
    rectangle2 <- data.frame(rectangle2, stringsAsFactors = FALSE)
     
    # Now let's deal with the text
    onTop <- gcDestination(lon = lon, lat = lat, bearing = 0, dist = distanceLegend, dist.units = dist.units, model = "WGS84")
    onTop2 <- onTop3 <- onTop
    onTop2[1,"long"] <- bottomRight[1,"long"]
    onTop3[1,"long"] <- bottomRight2[1,"long"]
     
    legend <- rbind(onTop, onTop2, onTop3)
    legend <- data.frame(cbind(legend, text = c(0, distanceLon, distanceLon*2)), stringsAsFactors = FALSE, row.names = NULL)
    return(list(rectangle = rectangle, rectangle2 = rectangle2, legend = legend))
}

#
# Result #
#--------#
# Returns a list containing :
#   - res : coordinates to draw an arrow ;
#   - coordinates of the middle of the arrow (where the "N" will be plotted).
#
# Arguments : #
#-------------#
# scaleBar : result of createScaleBar() ;
# length : desired length of the arrow ;
# distance : distance between legend rectangles and the bottom of the arrow ;
# dist.units : units of distance "km" (kilometers) (default), "nm" (nautical miles), "mi" (statute miles).
createOrientationArrow <- function(scaleBar, length, distance = 1, dist.units = "km"){
    lon <- scaleBar$rectangle2[1,1]
    lat <- scaleBar$rectangle2[1,2]
     
    # Bottom point of the arrow
    begPoint <- gcDestination(lon = lon, lat = lat, bearing = 0, dist = distance, dist.units = dist.units, model = "WGS84")
    lon <- begPoint[1,"long"]
    lat <- begPoint[1,"lat"]
     
    # Let us create the endpoint
    onTop <- gcDestination(lon = lon, lat = lat, bearing = 0, dist = length, dist.units = dist.units, model = "WGS84")
     
    leftArrow <- gcDestination(lon = onTop[1,"long"], lat = onTop[1,"lat"], bearing = 225, dist = length/5, dist.units = dist.units, model = "WGS84")
     
    rightArrow <- gcDestination(lon = onTop[1,"long"], lat = onTop[1,"lat"], bearing = 135, dist = length/5, dist.units = dist.units, model = "WGS84")
     
    res <- rbind(
            cbind(x = lon, y = lat, xend = onTop[1,"long"], yend = onTop[1,"lat"]),
            cbind(x = leftArrow[1,"long"], y = leftArrow[1,"lat"], xend = onTop[1,"long"], yend = onTop[1,"lat"]),
            cbind(x = rightArrow[1,"long"], y = rightArrow[1,"lat"], xend = onTop[1,"long"], yend = onTop[1,"lat"]))
     
    res <- as.data.frame(res, stringsAsFactors = FALSE)
     
    # Coordinates from which "N" will be plotted
    coordsN <- cbind(x = lon, y = (lat + onTop[1,"lat"])/2)
     
    return(list(res = res, coordsN = coordsN))
}

#
# Result #
#--------#
# This function enables to draw a scale bar on a ggplot object, and optionally an orientation arrow #
# Arguments : #
#-------------#
# lon, lat : longitude and latitude of the bottom left point of the first rectangle to draw ;
# distanceLon : length of each rectangle ;
# distanceLat : width of each rectangle ;
# distanceLegend : distance between rectangles and legend texts ;
# dist.units : units of distance "km" (kilometers) (by default), "nm" (nautical miles), "mi" (statute miles) ;
# rec.fill, rec2.fill : filling colour of the rectangles (default to white, and black, resp.);
# rec.colour, rec2.colour : colour of the rectangles (default to black for both);
# legend.colour : legend colour (default to black);
# legend.size : legend size (default to 3);
# orientation : (boolean) if TRUE (default), adds an orientation arrow to the plot ;
# arrow.length : length of the arrow (default to 500 km) ;
# arrow.distance : distance between the scale bar and the bottom of the arrow (default to 300 km) ;
# arrow.North.size : size of the "N" letter (default to 6).
scaleBar <- function(lon, lat, distanceLon, distanceLat, distanceLegend, dist.unit = "km", rec.fill = "white", rec.colour = "black", rec2.fill = "black", rec2.colour = "black", legend.colour = "black", legend.size = 3, orientation = TRUE, arrow.length = 500, arrow.distance = 300, arrow.North.size = 6){
    laScaleBar <- createScaleBar(lon = lon, lat = lat, distanceLon = distanceLon, distanceLat = distanceLat, distanceLegend = distanceLegend, dist.unit = dist.unit)
    # First rectangle
    rectangle1 <- geom_polygon(data = laScaleBar$rectangle, aes(x = lon, y = lat), fill = rec.fill, colour = rec.colour)
     
    # Second rectangle
    rectangle2 <- geom_polygon(data = laScaleBar$rectangle2, aes(x = lon, y = lat), fill = rec2.fill, colour = rec2.colour)
     
    # Legend
    scaleBarLegend <- annotate("text", label = paste(laScaleBar$legend[,"text"], dist.unit, sep=""), x = laScaleBar$legend[,"long"], y = laScaleBar$legend[,"lat"], size = legend.size, colour = legend.colour, family = "serif")
     
    res <- list(rectangle1, rectangle2, scaleBarLegend)
     
    if(orientation){# Add an arrow pointing North
        coordsArrow <- createOrientationArrow(scaleBar = laScaleBar, length = arrow.length, distance = arrow.distance, dist.unit = dist.unit)
        arrow <- list(geom_segment(data = coordsArrow$res, aes(x = x, y = y, xend = xend, yend = yend)), annotate("text", label = "N", x = coordsArrow$coordsN[1,"x"], y = coordsArrow$coordsN[1,"y"], size = arrow.North.size, colour = "black"))
        res <- c(res, arrow)
    }
    return(res)
}
```

Multiplot function

```{r}
# Multiple plot function
#
# ggplot objects can be passed in ..., or to plotlist (as a list of ggplot objects)
# - cols:   Number of columns in layout
# - layout: A matrix specifying the layout. If present, 'cols' is ignored.
#
# If the layout is something like matrix(c(1,2,3,3), nrow=2, byrow=TRUE),
# then plot 1 will go in the upper left, 2 will go in the upper right, and
# 3 will go all the way across the bottom.
#
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  require(grid)
  
  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)
  
  numPlots = length(plots)
  
  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                     ncol = cols, nrow = ceiling(numPlots/cols))
  }
  
  if (numPlots==1) {
    print(plots[[1]])
    
  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))
    
    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))
      
      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}
```



Plot the map

```{r, echo=FALSE}

annotations <- data.frame (label = c ("Kilindoni", "Ras Kisimani", "Ras Mbisi"),
                           x = c (39.675, 39.6, 39.71), 
                           y = c (-7.9, -7.955, -7.825))

insets <- qplot (data = land, x = lon, y = lat, group = trksegID, geom = "polygon")+ theme (legend.position = "none", text = element_text (family = "serif"), plot.margin = unit (c (0,0,0,0), "mm")) + theme(plot.background = element_rect(colour = "black", fill = c(0,0,0,0))) + coord_map ( ) + theme_linedraw () + labs (x = NULL, y= NULL)
insets <- ggplotGrob (insets)

rptheme <- theme_linedraw () + theme (legend.position = c (0,1), text = element_text (family = "serif"), legend.justification = c (0,1), legend.title.align = 0.5, legend.text.align = 0.5, legend.box.just = "left", legend.title = element_text(face = "italic", size = 8),axis.title = element_text(size = 8),axis.text = element_text(size = 8), text = element_text (),legend.text = element_text(size = 8), panel.grid = element_line (colour = "gray"), panel.grid.major = element_line (colour = "gray"), panel.grid.minor = element_line (colour = "gray"), plot.margin = unit (c (0,2,0,0), "pt"))

del = -0.01
p3 <- ggplot (data = land) + stat_binhex(data = tracks.standard, aes (x = lon, y = lat, alpha = log (..count..)), fill = "#006F51") +
  geom_polygon (data = land, aes (x = lon, y = lat, group = trksegID),fill = "#555555") + 
  geom_path (data = isobath, aes (x = lon, y = lat, group = trksegID), alpha = 0.8, linetype = 2, size = 0.2) +
  geom_point (data = receivers, aes (x = lon, y = lat), size = 1.5, colour = "#333333") + coord_map (xlim = c(39.45+del,39.78+del), ylim = c(-8,-7.77)) + xlab ("longitude") + ylab ("latitude") + scale_fill_continuous (guide = "none") + scale_alpha ("survey time (hrs)", breaks = c(0,2,4,6), labels = c ("< 0.5", "0.5 - 5", "5 - 20", "> 20"))   + guides(linetype = guide_legend(title=NULL, order = 2), shape = guide_legend(title=NULL, order = 3), alpha = guide_legend(order = 1)) + rptheme + scaleBar (lon = 39.46, lat = -7.99, distanceLon = 5, distanceLat = 0.5, distanceLegend = 1.5, dist.unit = "km", orientation  = FALSE, legend.size = 2.8)
# + geom_point (aes (x = 39.665, y = -7.915), colour = "white", shape = 8) + annotate ("text", x = 39.67, y = -7.92, label = "Kilindoni", family = "serif", colour = "white", angle = 44, vjust = 1, hjust = 0.45, size = 3)
ggsave ("map.pdf", width = 9, height = 9/sqrt(2), units = "cm", pointsize = 8)


```

We have the main map for mafia, now we plot another one showing the Mafia in the general context of East Africa

```{r}
# Load list of countries
countries <- read.csv ("../Raw Data/Map/2014-10-17.dump.countrylist.net.csv", sep = ";") %>% tbl_df()
african.countries <- filter (countries, continent == "Africa")$name %>% as.character () %>% strsplit (split = ",") %>% lapply (function(x) x[1]) %>% unlist () %>%
  c ("Libya", "Zaire", "Ivory")
west.african.countries <- c("Tanzania", "Kenya", "Mozambique", "France:Ile de Mayotte", "Comoros", "Madagascar")
# Load high resolution map and filter only african countries
africa <- map ("world", african.countries,
               plot = F, fill = T) %>% 
  fortify () %>% tbl_df ()
west.africa <- map ("worldHires", west.african.countries,
               plot = F, fill = T) %>% 
  fortify () %>% tbl_df ()
```

Plot maps

```{r}
# Region
p1 <- ggplot (west.africa, aes (x = long, y = lat, group = group)) + geom_polygon (fill = "#555555")  + coord_map(xlim = c (37.2, 41.2), ylim  =c(-4.4, -8.5)) + rptheme + xlab ("") + ylab ("")  + theme (plot.margin = unit (c (0,2,-65,0), "pt")) + geom_rect (aes (xmax = 39.78+del +0.1, xmin = 39.45+del-0.1, ymax = -7.77+0.1, ymin = -8-0.1), fill = "transparent", colour = "black", size = 0.5)

# Africa
p2 <- ggplot (africa, aes (x = long, y = lat, group = group)) + geom_polygon (fill = "#555555")  + coord_map(xlim = c (-20, 55), ylim  =c(-39, 39)) + rptheme + xlab ("") + ylab ("") + theme (plot.margin = unit (c (0,0,-65,6), "pt")) + geom_rect (aes (xmax = 42.2, xmin = 36.2, ymax = -3.2, ymin = -9.5), fill = "transparent", colour = "black", size = 0.5)

pdf ("fig1_b.pdf", width = 3.5433, height = 3.5433/sqrt(2)*2, pointsize = 8)
multiplot (p2, p1, p3, layout = matrix (c (1,2,3,3), ncol = 2, byrow = T))
dev.off ()

```


## Residency and model output plots


```{r}
load ("prediction_dataframes1.RData")
load ("prediction_dataframes2.RData")
load ("residency_prop.RData")

# Plot probabilities for just one initial date
p1 <- ggplot(pred.date, aes (x = date.2)) + 
  geom_line (aes (y = fit, colour = data))  + 
  rptheme + 
  geom_ribbon (aes (ymin = fit - se, ymax = fit + se, fill = data), alpha = 0.15) +
  scale_fill_manual (values = c("#006F51", "#000000")) +
  scale_colour_manual (values = c("#006F51", "#000000")) +
  xlab ("") + ylab ("re-capture probability") + theme (plot.margin = unit (c (-8,2,0,4), "pt"), legend.title = element_blank(),legend.position = c (1,1), legend.justification = c (1,1), legend.text.align = 0, plot.title = element_text (vjust = -2, size = 8, hjust = 0.03, face = "italic")) + ggtitle ("(a)") + coord_cartesian (xlim = c (min (residency$date.week), max (residency$date.week) ), ylim = c (-0.025, 0.75))

# Mean between day and night
p2 <- ggplot (dep.dis.pred.sum, aes (x = week, y = dept.fit)) + geom_line (colour = "#006F51") + geom_ribbon (aes (ymin = dept.fit - dept.se, ymax = dept.fit + dept.se), alpha = 0.15, fill = "#006F51") + rptheme  + xlab ("") + ylab ("depth (m)") + xlim (1,53) + coord_cartesian (xlim = c(1, 53)) + scale_y_reverse () + theme (plot.margin = unit (c (-4,2,0,6), "pt"), axis.title.x = element_blank(), plot.title = element_text (vjust = -2, size = 8, hjust = 0.03, face = "italic")) + ggtitle ("(c)")

p3 <- ggplot (dep.dis.pred.sum, aes (x = week, y = dist.fit)) + geom_line (colour = "#006F51") + geom_ribbon (aes (ymin = dist.fit - dist.se, ymax = dist.fit + dist.se), alpha = 0.15, fill = "#006F51") + rptheme + xlab ("week of the year") + ylab ("distance from shore (km)") + coord_cartesian (xlim = c(1, 53)) + scale_y_continuous (breaks = c (2,4,6,8), labels = c("2","4","6","8")) + theme (plot.margin = unit (c (-10,2,0,10), "pt"), plot.title = element_text (vjust = -2, size = 8, hjust = 0.03, face = "italic")) + ggtitle ("(d)") 


p4 <- ggplot (residency, aes (x = date.week)) + geom_line (aes (y = p, colour = type)) + geom_ribbon (aes (ymin = cil, ymax = ciu, fill = type), alpha = 0.15) + rptheme + scale_fill_manual (values = c("#006F51", "#000000")) + scale_colour_manual (values = c("#006F51", "#000000")) + xlab ("date") + ylab ("prop. of days present")+ theme (plot.margin = unit (c (-10,2,8,0), "pt"), legend.title = element_blank(),legend.position = "none", legend.justification = c (1,1), legend.text.align = 0, plot.title = element_text (vjust = -2, size = 8, hjust = 0.03, face = "italic")) + coord_cartesian (xlim = c (min (residency$date.week), max (residency$date.week) ), ylim = c(0.08,1.11)) + ggtitle ("(b)") 

pdf ("fig2_d.pdf", width = 3.5433, height = 3.5433/sqrt(2)*2.5, pointsize = 8)
multiplot (p1, p4, p2, p3, layout = matrix (c (1,1,1,2,2,2,3,3,4,4), ncol = 1))
dev.off ()
 
```

# Tables

## Tagging detals

```{r}
ws.tags <- read.csv ("../Raw Data/WSTags_20140909.csv")
xtable (select (ws.tags, da, SEX, SIZE)) %>% print (type = "html")
```

